language: generic
sudo: required
services:
  - docker

before_install: 
  - docker build -t vairarchi/docker-react -f Dockerfile.dev .

script:
  - docker run vairarchi/docker-react npm run test -- --coverage